ui_print "**************************************************************"
ui_print "**************************************************************"
ui_print "Enable On Screen Nav-bar"
ui_print "by firefinchdev"
ui_print "**************************************************************"
ui_print "**************************************************************"
ui_print "This module enables On Screen Navigation Bar"